version: "3.7"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: child
      MYSQL_DATABASE: child
    volumes:
      - ./docs/static/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      
  childdebug:
    build: ./
    privileged: true
    user: child
    volumes:
      - type: bind
        source: ./
        target: /opt/child/
      - type: bind
        source: ./docker/child.conf
        target: /opt/child/child.conf
    ports:
      - 9999:9999
      - 8000:8000
    depends_on:
      - unrealircd
      - mysql

  unrealircd:
    build: ./docker/unrealircd/
    ports:
      - 6667:6667
      - 6697:6697
      - 6999:6999
    volumes:
      - ./docker/unrealircd/unrealircd.conf:/data/unrealircd/conf/unrealircd.conf
