jobs:
  build:
    docker:
      - image: gcc:7.5
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update && apt install -y cmake check
      - checkout:
      - run: cmake .
      - run: make
      - run: make test
