jobs:
  build:
    docker:
      - image: gcc:7.5
    environment:
      DEBIAN_FRONTEND: noninteractive
      CK_TAP_LOG_FILE_NAME: tests/results.tap
    steps:
      - run: apt update && apt install -y apt-transport-https ca-certificates gnupg software-properties-common wget
      - run: wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
      - run: apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && apt update && apt install -y cmake check
      - checkout:
      - run: cmake .
      - run: make
      - run: make test
      - store_artifacts:
          path: src/child
          destination: child
      - run: apt install -y npm && npm install tap-xunit -g && sleep 1 && chmod +x /usr/local/lib/node_modules/tap-xunit/bin/tap-xunit && cat tests/results.tap | tap-xunit > tests/results.xml
      - store_test_results:
          path: tests
