# Try to find libprom libraries
# https://github.com/digitalocean/prometheus-client-c
#
# LIBPROM_FOUND
# LIBPROM_INCLUDE_DIR
# LIBPROM_LIBRARY
# LIBPROMHTTP_FOUND
# LIBPROMHTTP_INCLUDE_DIR
# LIBPROMHTTP_LIBRARY
# LIBPROM_LIBRARIES
#

IF( NOT LIBPROM_FOUND )
	FIND_PATH(LIBPROM_INCLUDE_DIR prom.h)
	FIND_LIBRARY( LIBPROM_LIBRARY NAMES prom )

	IF (LIBPROM_INCLUDE_DIR AND LIBPROM_LIBRARY)
		SET (LIBPROM_FOUND TRUE)
		MESSAGE ( STATUS "Found libprom: ${LIBPROM_LIBRARY}" )
	ENDIF (LIBPROM_INCLUDE_DIR AND LIBPROM_LIBRARY)
ENDIF ( NOT LIBPROM_FOUND )

IF( NOT LIBPROMHTTP_FOUND )
	FIND_PATH(LIBPROMHTTP_INCLUDE_DIR promhttp.h)
	FIND_LIBRARY( LIBPROMHTTP_LIBRARY NAMES promhttp )

	IF (LIBPROMHTTP_INCLUDE_DIR AND LIBPROMHTTP_LIBRARY)
		SET (LIBPROMHTTP_FOUND TRUE)
		MESSAGE ( STATUS "Found libpromhttp: ${LIBPROMHTTP_LIBRARY}" )
	ENDIF (LIBPROMHTTP_INCLUDE_DIR AND LIBPROMHTTP_LIBRARY)
ENDIF ( NOT LIBPROMHTTP_FOUND )

SET (LIBPROM_LIBRARIES "${LIBPROM_LIBRARY}" "${LIBPROMHTTP_LIBRARY}")

MARK_AS_ADVANCED (LIBPROM_INCLUDE_DIR LIBPROMHTTP_INCLUDE_DIR LIBPROM_LIBRARY LIBPROMHTTP_LIBRARY)
